[project]
name = "tsetlinmachinesubjecttaggingpilot"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.13.4",
    "bs4==0.0.2",
    "certifi==2025.7.9",
    "charset-normalizer==3.4.2",
    "idna==3.10",
    "joblib==1.5.1",
    "mako==1.3.10",
    "markupsafe==3.0.2",
    "numpy==2.3.1",
    "pandas==2.3.1",
    "platformdirs==4.3.8",
    "pycoalescedtsetlinmachinecuda",
    "pycuda==2025.1.1",
    "pysparsecoalescedtsetlinmachinecuda",
    "python-dateutil==2.9.0.post0",
    "pytools==2025.2.1",
    "pytz==2025.2",
    "requests==2.32.4",
    "scikit-learn==1.7.0",
    "scipy==1.16.0",
    "setuptools==80.9.0",
    "siphash24==1.7",
    "six==1.17.0",
    "soupsieve==2.7",
    "threadpoolctl==3.6.0",
    "tqdm==4.67.1",
    "typing-extensions==4.14.1",
    "tzdata==2025.2",
    "urllib3==2.5.0",
]

[tool.uv.sources]
pycoalescedtsetlinmachinecuda = { path = "../../PyCoalescedTsetlinMachineCUDA/dist/pycoalescedtsetlinmachinecuda-0.1.9.tar.gz" }
pysparsecoalescedtsetlinmachinecuda = { path = "../../PySparseCoalescedTsetlinMachineCUDA/dist/pysparsecoalescedtsetlinmachinecuda-0.2.0.tar.gz" }
